# Generated by Django 3.1.7 on 2021-04-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210425_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='description',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
